// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwCmv3nWuLQfTUdEfojyFSInpS-hpsCT8',
    appId: '1:366663868922:web:d7733a52299e1e2f208443',
    messagingSenderId: '366663868922',
    projectId: 'otpauth-18ff0',
    authDomain: 'otpauth-18ff0.firebaseapp.com',
    storageBucket: 'otpauth-18ff0.appspot.com',
    measurementId: 'G-DWC6XEB1BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnhnXdVZEQfd5Vt_sHLJVHm8c8ma4x5SE',
    appId: '1:366663868922:android:a08f4934616ad679208443',
    messagingSenderId: '366663868922',
    projectId: 'otpauth-18ff0',
    storageBucket: 'otpauth-18ff0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR2JFoeGgOwhB_FV7fGm_C8CRngrFGbaE',
    appId: '1:366663868922:ios:bc6a7aaf9d7cb7a2208443',
    messagingSenderId: '366663868922',
    projectId: 'otpauth-18ff0',
    storageBucket: 'otpauth-18ff0.appspot.com',
    iosClientId: '366663868922-00s16503te7q6n0gu020ujp9tdn6n71q.apps.googleusercontent.com',
    iosBundleId: 'com.example.otpUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR2JFoeGgOwhB_FV7fGm_C8CRngrFGbaE',
    appId: '1:366663868922:ios:bc6a7aaf9d7cb7a2208443',
    messagingSenderId: '366663868922',
    projectId: 'otpauth-18ff0',
    storageBucket: 'otpauth-18ff0.appspot.com',
    iosClientId: '366663868922-00s16503te7q6n0gu020ujp9tdn6n71q.apps.googleusercontent.com',
    iosBundleId: 'com.example.otpUi',
  );
}
